# Generating htmltags.go
echo "// Code generated by htmltags.sh; DO NOT EDIT." > htmltags.go
echo >> htmltags.go
echo "package hypergo" >> htmltags.go
perl -nle '$t=lc; print "func $_(attrs ...string) *Node { return Element(`$t`, attrs...) }"' htmltags.txt >> htmltags.go
perl -nle '$t=lc; print "func (n *Node) $_(attrs ...string) *Node { return n.Element(`$t`, attrs...) }"' htmltags.txt >> htmltags.go
gofmt -w htmltags.go
