// Code generated by htmltags.sh; DO NOT EDIT.
package hypergo

func A(attrs ...string) *Node                    { return Element(`a`, attrs...) }
func Abbr(attrs ...string) *Node                 { return Element(`abbr`, attrs...) }
func Address(attrs ...string) *Node              { return Element(`address`, attrs...) }
func Area(attrs ...string) *Node                 { return Element(`area`, attrs...) }
func Article(attrs ...string) *Node              { return Element(`article`, attrs...) }
func Aside(attrs ...string) *Node                { return Element(`aside`, attrs...) }
func Audio(attrs ...string) *Node                { return Element(`audio`, attrs...) }
func B(attrs ...string) *Node                    { return Element(`b`, attrs...) }
func Base(attrs ...string) *Node                 { return Element(`base`, attrs...) }
func Bdi(attrs ...string) *Node                  { return Element(`bdi`, attrs...) }
func Bdo(attrs ...string) *Node                  { return Element(`bdo`, attrs...) }
func Blockquote(attrs ...string) *Node           { return Element(`blockquote`, attrs...) }
func Body(attrs ...string) *Node                 { return Element(`body`, attrs...) }
func Br(attrs ...string) *Node                   { return Element(`br`, attrs...) }
func Button(attrs ...string) *Node               { return Element(`button`, attrs...) }
func Canvas(attrs ...string) *Node               { return Element(`canvas`, attrs...) }
func Caption(attrs ...string) *Node              { return Element(`caption`, attrs...) }
func Cite(attrs ...string) *Node                 { return Element(`cite`, attrs...) }
func Code(attrs ...string) *Node                 { return Element(`code`, attrs...) }
func Col(attrs ...string) *Node                  { return Element(`col`, attrs...) }
func Colgroup(attrs ...string) *Node             { return Element(`colgroup`, attrs...) }
func Command(attrs ...string) *Node              { return Element(`command`, attrs...) }
func Data(attrs ...string) *Node                 { return Element(`data`, attrs...) }
func Datalist(attrs ...string) *Node             { return Element(`datalist`, attrs...) }
func Dd(attrs ...string) *Node                   { return Element(`dd`, attrs...) }
func Del(attrs ...string) *Node                  { return Element(`del`, attrs...) }
func Details(attrs ...string) *Node              { return Element(`details`, attrs...) }
func Dfn(attrs ...string) *Node                  { return Element(`dfn`, attrs...) }
func Div(attrs ...string) *Node                  { return Element(`div`, attrs...) }
func Dl(attrs ...string) *Node                   { return Element(`dl`, attrs...) }
func Dt(attrs ...string) *Node                   { return Element(`dt`, attrs...) }
func Em(attrs ...string) *Node                   { return Element(`em`, attrs...) }
func Embed(attrs ...string) *Node                { return Element(`embed`, attrs...) }
func Fieldset(attrs ...string) *Node             { return Element(`fieldset`, attrs...) }
func Figcaption(attrs ...string) *Node           { return Element(`figcaption`, attrs...) }
func Figure(attrs ...string) *Node               { return Element(`figure`, attrs...) }
func Footer(attrs ...string) *Node               { return Element(`footer`, attrs...) }
func Form(attrs ...string) *Node                 { return Element(`form`, attrs...) }
func H1(attrs ...string) *Node                   { return Element(`h1`, attrs...) }
func H2(attrs ...string) *Node                   { return Element(`h2`, attrs...) }
func H3(attrs ...string) *Node                   { return Element(`h3`, attrs...) }
func H4(attrs ...string) *Node                   { return Element(`h4`, attrs...) }
func H5(attrs ...string) *Node                   { return Element(`h5`, attrs...) }
func H6(attrs ...string) *Node                   { return Element(`h6`, attrs...) }
func Head(attrs ...string) *Node                 { return Element(`head`, attrs...) }
func Header(attrs ...string) *Node               { return Element(`header`, attrs...) }
func Hgroup(attrs ...string) *Node               { return Element(`hgroup`, attrs...) }
func Hr(attrs ...string) *Node                   { return Element(`hr`, attrs...) }
func Html(attrs ...string) *Node                 { return Element(`html`, attrs...) }
func I(attrs ...string) *Node                    { return Element(`i`, attrs...) }
func Iframe(attrs ...string) *Node               { return Element(`iframe`, attrs...) }
func Img(attrs ...string) *Node                  { return Element(`img`, attrs...) }
func Input(attrs ...string) *Node                { return Element(`input`, attrs...) }
func Ins(attrs ...string) *Node                  { return Element(`ins`, attrs...) }
func Kbd(attrs ...string) *Node                  { return Element(`kbd`, attrs...) }
func Keygen(attrs ...string) *Node               { return Element(`keygen`, attrs...) }
func Label(attrs ...string) *Node                { return Element(`label`, attrs...) }
func Legend(attrs ...string) *Node               { return Element(`legend`, attrs...) }
func Li(attrs ...string) *Node                   { return Element(`li`, attrs...) }
func Link(attrs ...string) *Node                 { return Element(`link`, attrs...) }
func Main(attrs ...string) *Node                 { return Element(`main`, attrs...) }
func Map(attrs ...string) *Node                  { return Element(`map`, attrs...) }
func Mark(attrs ...string) *Node                 { return Element(`mark`, attrs...) }
func Menu(attrs ...string) *Node                 { return Element(`menu`, attrs...) }
func Menuitem(attrs ...string) *Node             { return Element(`menuitem`, attrs...) }
func Meta(attrs ...string) *Node                 { return Element(`meta`, attrs...) }
func Meter(attrs ...string) *Node                { return Element(`meter`, attrs...) }
func Nav(attrs ...string) *Node                  { return Element(`nav`, attrs...) }
func Noscript(attrs ...string) *Node             { return Element(`noscript`, attrs...) }
func Object(attrs ...string) *Node               { return Element(`object`, attrs...) }
func Ol(attrs ...string) *Node                   { return Element(`ol`, attrs...) }
func Optgroup(attrs ...string) *Node             { return Element(`optgroup`, attrs...) }
func Option(attrs ...string) *Node               { return Element(`option`, attrs...) }
func Output(attrs ...string) *Node               { return Element(`output`, attrs...) }
func P(attrs ...string) *Node                    { return Element(`p`, attrs...) }
func Param(attrs ...string) *Node                { return Element(`param`, attrs...) }
func Picture(attrs ...string) *Node              { return Element(`picture`, attrs...) }
func Pre(attrs ...string) *Node                  { return Element(`pre`, attrs...) }
func Progress(attrs ...string) *Node             { return Element(`progress`, attrs...) }
func Q(attrs ...string) *Node                    { return Element(`q`, attrs...) }
func Rb(attrs ...string) *Node                   { return Element(`rb`, attrs...) }
func Rp(attrs ...string) *Node                   { return Element(`rp`, attrs...) }
func Rt(attrs ...string) *Node                   { return Element(`rt`, attrs...) }
func Rtc(attrs ...string) *Node                  { return Element(`rtc`, attrs...) }
func Ruby(attrs ...string) *Node                 { return Element(`ruby`, attrs...) }
func S(attrs ...string) *Node                    { return Element(`s`, attrs...) }
func Samp(attrs ...string) *Node                 { return Element(`samp`, attrs...) }
func Script(attrs ...string) *Node               { return Element(`script`, attrs...) }
func Section(attrs ...string) *Node              { return Element(`section`, attrs...) }
func Select(attrs ...string) *Node               { return Element(`select`, attrs...) }
func Small(attrs ...string) *Node                { return Element(`small`, attrs...) }
func Source(attrs ...string) *Node               { return Element(`source`, attrs...) }
func Span(attrs ...string) *Node                 { return Element(`span`, attrs...) }
func Strong(attrs ...string) *Node               { return Element(`strong`, attrs...) }
func Style(attrs ...string) *Node                { return Element(`style`, attrs...) }
func Sub(attrs ...string) *Node                  { return Element(`sub`, attrs...) }
func Summary(attrs ...string) *Node              { return Element(`summary`, attrs...) }
func Sup(attrs ...string) *Node                  { return Element(`sup`, attrs...) }
func Table(attrs ...string) *Node                { return Element(`table`, attrs...) }
func Tbody(attrs ...string) *Node                { return Element(`tbody`, attrs...) }
func Td(attrs ...string) *Node                   { return Element(`td`, attrs...) }
func Template(attrs ...string) *Node             { return Element(`template`, attrs...) }
func Textarea(attrs ...string) *Node             { return Element(`textarea`, attrs...) }
func Tfoot(attrs ...string) *Node                { return Element(`tfoot`, attrs...) }
func Th(attrs ...string) *Node                   { return Element(`th`, attrs...) }
func Thead(attrs ...string) *Node                { return Element(`thead`, attrs...) }
func Time(attrs ...string) *Node                 { return Element(`time`, attrs...) }
func Title(attrs ...string) *Node                { return Element(`title`, attrs...) }
func Tr(attrs ...string) *Node                   { return Element(`tr`, attrs...) }
func Track(attrs ...string) *Node                { return Element(`track`, attrs...) }
func U(attrs ...string) *Node                    { return Element(`u`, attrs...) }
func Ul(attrs ...string) *Node                   { return Element(`ul`, attrs...) }
func Var(attrs ...string) *Node                  { return Element(`var`, attrs...) }
func Video(attrs ...string) *Node                { return Element(`video`, attrs...) }
func Wbr(attrs ...string) *Node                  { return Element(`wbr`, attrs...) }
func (n *Node) A(attrs ...string) *Node          { return n.Element(`a`, attrs...) }
func (n *Node) Abbr(attrs ...string) *Node       { return n.Element(`abbr`, attrs...) }
func (n *Node) Address(attrs ...string) *Node    { return n.Element(`address`, attrs...) }
func (n *Node) Area(attrs ...string) *Node       { return n.Element(`area`, attrs...) }
func (n *Node) Article(attrs ...string) *Node    { return n.Element(`article`, attrs...) }
func (n *Node) Aside(attrs ...string) *Node      { return n.Element(`aside`, attrs...) }
func (n *Node) Audio(attrs ...string) *Node      { return n.Element(`audio`, attrs...) }
func (n *Node) B(attrs ...string) *Node          { return n.Element(`b`, attrs...) }
func (n *Node) Base(attrs ...string) *Node       { return n.Element(`base`, attrs...) }
func (n *Node) Bdi(attrs ...string) *Node        { return n.Element(`bdi`, attrs...) }
func (n *Node) Bdo(attrs ...string) *Node        { return n.Element(`bdo`, attrs...) }
func (n *Node) Blockquote(attrs ...string) *Node { return n.Element(`blockquote`, attrs...) }
func (n *Node) Body(attrs ...string) *Node       { return n.Element(`body`, attrs...) }
func (n *Node) Br(attrs ...string) *Node         { return n.Element(`br`, attrs...) }
func (n *Node) Button(attrs ...string) *Node     { return n.Element(`button`, attrs...) }
func (n *Node) Canvas(attrs ...string) *Node     { return n.Element(`canvas`, attrs...) }
func (n *Node) Caption(attrs ...string) *Node    { return n.Element(`caption`, attrs...) }
func (n *Node) Cite(attrs ...string) *Node       { return n.Element(`cite`, attrs...) }
func (n *Node) Code(attrs ...string) *Node       { return n.Element(`code`, attrs...) }
func (n *Node) Col(attrs ...string) *Node        { return n.Element(`col`, attrs...) }
func (n *Node) Colgroup(attrs ...string) *Node   { return n.Element(`colgroup`, attrs...) }
func (n *Node) Command(attrs ...string) *Node    { return n.Element(`command`, attrs...) }
func (n *Node) Data(attrs ...string) *Node       { return n.Element(`data`, attrs...) }
func (n *Node) Datalist(attrs ...string) *Node   { return n.Element(`datalist`, attrs...) }
func (n *Node) Dd(attrs ...string) *Node         { return n.Element(`dd`, attrs...) }
func (n *Node) Del(attrs ...string) *Node        { return n.Element(`del`, attrs...) }
func (n *Node) Details(attrs ...string) *Node    { return n.Element(`details`, attrs...) }
func (n *Node) Dfn(attrs ...string) *Node        { return n.Element(`dfn`, attrs...) }
func (n *Node) Div(attrs ...string) *Node        { return n.Element(`div`, attrs...) }
func (n *Node) Dl(attrs ...string) *Node         { return n.Element(`dl`, attrs...) }
func (n *Node) Dt(attrs ...string) *Node         { return n.Element(`dt`, attrs...) }
func (n *Node) Em(attrs ...string) *Node         { return n.Element(`em`, attrs...) }
func (n *Node) Embed(attrs ...string) *Node      { return n.Element(`embed`, attrs...) }
func (n *Node) Fieldset(attrs ...string) *Node   { return n.Element(`fieldset`, attrs...) }
func (n *Node) Figcaption(attrs ...string) *Node { return n.Element(`figcaption`, attrs...) }
func (n *Node) Figure(attrs ...string) *Node     { return n.Element(`figure`, attrs...) }
func (n *Node) Footer(attrs ...string) *Node     { return n.Element(`footer`, attrs...) }
func (n *Node) Form(attrs ...string) *Node       { return n.Element(`form`, attrs...) }
func (n *Node) H1(attrs ...string) *Node         { return n.Element(`h1`, attrs...) }
func (n *Node) H2(attrs ...string) *Node         { return n.Element(`h2`, attrs...) }
func (n *Node) H3(attrs ...string) *Node         { return n.Element(`h3`, attrs...) }
func (n *Node) H4(attrs ...string) *Node         { return n.Element(`h4`, attrs...) }
func (n *Node) H5(attrs ...string) *Node         { return n.Element(`h5`, attrs...) }
func (n *Node) H6(attrs ...string) *Node         { return n.Element(`h6`, attrs...) }
func (n *Node) Head(attrs ...string) *Node       { return n.Element(`head`, attrs...) }
func (n *Node) Header(attrs ...string) *Node     { return n.Element(`header`, attrs...) }
func (n *Node) Hgroup(attrs ...string) *Node     { return n.Element(`hgroup`, attrs...) }
func (n *Node) Hr(attrs ...string) *Node         { return n.Element(`hr`, attrs...) }
func (n *Node) Html(attrs ...string) *Node       { return n.Element(`html`, attrs...) }
func (n *Node) I(attrs ...string) *Node          { return n.Element(`i`, attrs...) }
func (n *Node) Iframe(attrs ...string) *Node     { return n.Element(`iframe`, attrs...) }
func (n *Node) Img(attrs ...string) *Node        { return n.Element(`img`, attrs...) }
func (n *Node) Input(attrs ...string) *Node      { return n.Element(`input`, attrs...) }
func (n *Node) Ins(attrs ...string) *Node        { return n.Element(`ins`, attrs...) }
func (n *Node) Kbd(attrs ...string) *Node        { return n.Element(`kbd`, attrs...) }
func (n *Node) Keygen(attrs ...string) *Node     { return n.Element(`keygen`, attrs...) }
func (n *Node) Label(attrs ...string) *Node      { return n.Element(`label`, attrs...) }
func (n *Node) Legend(attrs ...string) *Node     { return n.Element(`legend`, attrs...) }
func (n *Node) Li(attrs ...string) *Node         { return n.Element(`li`, attrs...) }
func (n *Node) Link(attrs ...string) *Node       { return n.Element(`link`, attrs...) }
func (n *Node) Main(attrs ...string) *Node       { return n.Element(`main`, attrs...) }
func (n *Node) Map(attrs ...string) *Node        { return n.Element(`map`, attrs...) }
func (n *Node) Mark(attrs ...string) *Node       { return n.Element(`mark`, attrs...) }
func (n *Node) Menu(attrs ...string) *Node       { return n.Element(`menu`, attrs...) }
func (n *Node) Menuitem(attrs ...string) *Node   { return n.Element(`menuitem`, attrs...) }
func (n *Node) Meta(attrs ...string) *Node       { return n.Element(`meta`, attrs...) }
func (n *Node) Meter(attrs ...string) *Node      { return n.Element(`meter`, attrs...) }
func (n *Node) Nav(attrs ...string) *Node        { return n.Element(`nav`, attrs...) }
func (n *Node) Noscript(attrs ...string) *Node   { return n.Element(`noscript`, attrs...) }
func (n *Node) Object(attrs ...string) *Node     { return n.Element(`object`, attrs...) }
func (n *Node) Ol(attrs ...string) *Node         { return n.Element(`ol`, attrs...) }
func (n *Node) Optgroup(attrs ...string) *Node   { return n.Element(`optgroup`, attrs...) }
func (n *Node) Option(attrs ...string) *Node     { return n.Element(`option`, attrs...) }
func (n *Node) Output(attrs ...string) *Node     { return n.Element(`output`, attrs...) }
func (n *Node) P(attrs ...string) *Node          { return n.Element(`p`, attrs...) }
func (n *Node) Param(attrs ...string) *Node      { return n.Element(`param`, attrs...) }
func (n *Node) Picture(attrs ...string) *Node    { return n.Element(`picture`, attrs...) }
func (n *Node) Pre(attrs ...string) *Node        { return n.Element(`pre`, attrs...) }
func (n *Node) Progress(attrs ...string) *Node   { return n.Element(`progress`, attrs...) }
func (n *Node) Q(attrs ...string) *Node          { return n.Element(`q`, attrs...) }
func (n *Node) Rb(attrs ...string) *Node         { return n.Element(`rb`, attrs...) }
func (n *Node) Rp(attrs ...string) *Node         { return n.Element(`rp`, attrs...) }
func (n *Node) Rt(attrs ...string) *Node         { return n.Element(`rt`, attrs...) }
func (n *Node) Rtc(attrs ...string) *Node        { return n.Element(`rtc`, attrs...) }
func (n *Node) Ruby(attrs ...string) *Node       { return n.Element(`ruby`, attrs...) }
func (n *Node) S(attrs ...string) *Node          { return n.Element(`s`, attrs...) }
func (n *Node) Samp(attrs ...string) *Node       { return n.Element(`samp`, attrs...) }
func (n *Node) Script(attrs ...string) *Node     { return n.Element(`script`, attrs...) }
func (n *Node) Section(attrs ...string) *Node    { return n.Element(`section`, attrs...) }
func (n *Node) Select(attrs ...string) *Node     { return n.Element(`select`, attrs...) }
func (n *Node) Small(attrs ...string) *Node      { return n.Element(`small`, attrs...) }
func (n *Node) Source(attrs ...string) *Node     { return n.Element(`source`, attrs...) }
func (n *Node) Span(attrs ...string) *Node       { return n.Element(`span`, attrs...) }
func (n *Node) Strong(attrs ...string) *Node     { return n.Element(`strong`, attrs...) }
func (n *Node) Style(attrs ...string) *Node      { return n.Element(`style`, attrs...) }
func (n *Node) Sub(attrs ...string) *Node        { return n.Element(`sub`, attrs...) }
func (n *Node) Summary(attrs ...string) *Node    { return n.Element(`summary`, attrs...) }
func (n *Node) Sup(attrs ...string) *Node        { return n.Element(`sup`, attrs...) }
func (n *Node) Table(attrs ...string) *Node      { return n.Element(`table`, attrs...) }
func (n *Node) Tbody(attrs ...string) *Node      { return n.Element(`tbody`, attrs...) }
func (n *Node) Td(attrs ...string) *Node         { return n.Element(`td`, attrs...) }
func (n *Node) Template(attrs ...string) *Node   { return n.Element(`template`, attrs...) }
func (n *Node) Textarea(attrs ...string) *Node   { return n.Element(`textarea`, attrs...) }
func (n *Node) Tfoot(attrs ...string) *Node      { return n.Element(`tfoot`, attrs...) }
func (n *Node) Th(attrs ...string) *Node         { return n.Element(`th`, attrs...) }
func (n *Node) Thead(attrs ...string) *Node      { return n.Element(`thead`, attrs...) }
func (n *Node) Time(attrs ...string) *Node       { return n.Element(`time`, attrs...) }
func (n *Node) Title(attrs ...string) *Node      { return n.Element(`title`, attrs...) }
func (n *Node) Tr(attrs ...string) *Node         { return n.Element(`tr`, attrs...) }
func (n *Node) Track(attrs ...string) *Node      { return n.Element(`track`, attrs...) }
func (n *Node) U(attrs ...string) *Node          { return n.Element(`u`, attrs...) }
func (n *Node) Ul(attrs ...string) *Node         { return n.Element(`ul`, attrs...) }
func (n *Node) Var(attrs ...string) *Node        { return n.Element(`var`, attrs...) }
func (n *Node) Video(attrs ...string) *Node      { return n.Element(`video`, attrs...) }
func (n *Node) Wbr(attrs ...string) *Node        { return n.Element(`wbr`, attrs...) }
